version: "3"

services:
  conditional:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conditional
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: conditional
    volumes:
      - ./:/var/www/html
    networks:
      - conditional-network

#Docker Networks
networks:
  conditional-network:
    driver: bridge